name: Reveal Environment Secret
on: workflow_dispatch # Allows you to trigger it manually

jobs:
  reveal:
    runs-on: ubuntu-latest
    environment: "CI/CD"
    steps:
      - name: Reveal Secret with Spaces
        env:
          STAGING_HOST: ${{ secrets.STAGING_DOKKU_HOST }}
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_DOKKU_HOST }}
        run: |
          # Modifies string to place spaces between letters so GitHub doesn't recognize the exact string
          echo "$STAGING_HOST" | sed 's/./& /g'
          echo "$PRODUCTION_HOST" | sed 's/./& /g'

      - name: Reveal Secret via Base64 Encoding
        env:
          STAGING_HOST: ${{ secrets.STAGING_DOKKU_HOST }}
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_DOKKU_HOST }}
        run: |
          # Encodes the value into base64 string
          echo "$STAGING_HOST" | base64
          echo "$PRODUCTION_HOST" | base64